### ISSUE TITLE
not able to install the helm chart

### ISSUE THREAD

**Issue by MridulS** [bitnik/binder_launches#11]
```
$ kubectl logs binder-launches-XXXXXXXXXXX

> binder-launches@0.1.0 start-server
> node server/server.js

node:net:1486
  throw new ERR_INVALID_ARG_VALUE('options', options);
  ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'options' is invalid. Received { port: true }
    at new NodeError (node:internal/errors:329:5)
    at Server.listen (node:net:1486:9)
    at Function.listen (/usr/src/app/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/usr/src/app/server/server.js:252:5)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ERR_INVALID_ARG_VALUE'
}
npm ERR! code 1
npm ERR! path /usr/src/app
npm ERR! command failed
npm ERR! command sh -c node server/server.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-13T20_04_16_629Z-debug.log
```

@bitnik I tried to install the new chart, any ideas what's going wrong here?

**Comment by MridulS** [comment]
ahhhh closing this, this is my stupid typo locally.
